### ISSUE TITLE
Missing ResponseCode: LONGENTRIES from METADATA extension

### ISSUE THREAD

**Issue by jonhoo** [djc/tokio-imap#113]
The METADATA IMAP extension defines a LONGENTRIES response code that should probably be added to `ResponseCode`: https://tools.ietf.org/html/rfc5464#section-4.2.1

**Comment by jonhoo** [comment]
It also defines the `METADATA TOOMANY` and `METADATA MAXSIZE` `ResponseCode`s:
```
      resp-text-code    =/ "METADATA" SP "LONGENTRIES" SP number
                             ; new response codes for GETMETADATA

      resp-text-code    =/ "METADATA" SP ("MAXSIZE" SP number /
                                          "TOOMANY" / "NOPRIVATE")
                          ; new response codes for SETMETADATA
                          ; failures
```

**Comment by djc** [comment]
I'd be happy to have these added, not quite motivated enough to add them to myself right now.
