### ISSUE TITLE
Store borrowed fields using `Cow`

### ISSUE THREAD

**Issue by jonhoo** [djc/tokio-imap#114]
The current implementation stores `&'a T` for many fields (I'm particularly thinking of [`ResponseCode`](https://docs.rs/imap-proto/0.12/imap_proto/types/enum.ResponseCode.html), but it applies to others). That makes a lot of sense for parsing, but makes it hard to clone the type to keep it beyond the parsing step.

This could be mitigated by replacing every `&'a T` with `Cow<'a, T>` and then adding
```rust
impl<'a> ResponseCode<'a> {
   pub fn into_owned(self) -> ResponseCode<'static> { }
}
```
to each such type, which just maps all the internal `Cow`'s into their owned variants.

That would make these types a lot more ergonomic to use in more contexts, and would avoid forcing downstream libraries to keep their own owned versions of these types!

**Comment by djc** [comment]
I'd be happy to review PRs in this direction!

**Comment by jonhoo** [comment]
:tada: 

PR up in https://github.com/djc/tokio-imap/pull/115, though of course I then realized I was operating on top of an old version of `master`...
