### ISSUE TITLE
[Suggestion] RFC 5256 - SORT command

### ISSUE THREAD

**Issue by soywod** [djc/tokio-imap#117]
It could be nice to parse the `SORT` command as defined in the [RFC-5256](https://tools.ietf.org/html/rfc5256#section-3). I can propose a PR!

**Comment by djc** [comment]
Happy to review your PR!

**Comment by soywod** [comment]
Let me know when a new version is available, so I can use it in my tool!

**Comment by djc** [comment]
I noticed you have some other features on the himalaya roadmap, do any of them require further imap-proto changes? If so, I'd prefer to batch them all up in a single release.

**Comment by soywod** [comment]
The potential changes I see are about this same rfc5256 (the thread section). I don't plan to implement it for now (not even for the v1), so I would say I have nothing more!

**Comment by djc** [comment]
I've pushed out imap-proto 0.13.1.
