### ISSUE TITLE
[Question] Difference between Sender and From from Envelope

### ISSUE THREAD

**Issue by TornaxO7** [djc/tokio-imap#127]
As the title says, your [Envelope struct](https://docs.rs/imap-proto/0.14.3/imap_proto/types/struct.Envelope.html) includes the fields: `from` and `sender` but what's their difference?

Also what does [`adl`](https://docs.rs/imap-proto/0.14.3/imap_proto/types/struct.Address.html#structfield.adl) mean?

**Comment by djc** [comment]
I added some documentation about the difference between `from` and `sender`. In general, you should defer to the appropriate RFC -- in this case, mostly 3501 (IMAP), though the finer details for this stuff actually live in 2822.

I looked up a little bit what `adl` is actually used for, but couldn't quickly find any examples. I think this was part of RFC 822 and is part of the "obsolete" syntax specified in RFC 2822. You can probably mostly ignore it.

In general, this crate implements a parser for IMAP, but I don't see it as my responsibility to replicate documentation for all of its semantics in my spare time.
