### ISSUE TITLE
Missing references attribute in Envelope struct

### ISSUE THREAD

**Issue by TornaxO7** [djc/tokio-imap#129]
Hello, according to the [RFC5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4) there should be a `References:`  field but it doesn't exist in the [envelope struct](https://github.com/djc/tokio-imap/blob/main/imap-proto/src/types.rs#L567). Adding this field would also fix [this issue](https://github.com/jonhoo/rust-imap/issues/209).

**Comment by TornaxO7** [comment]
I can try to create a pull request for this "problem".

**Comment by djc** [comment]
Please first find the reference in the IMAP RFC, rather than the MIME-related RFCs.

**Comment by TornaxO7** [comment]
Do you man [this](https://datatracker.ietf.org/doc/html/rfc2822#section-3.6)?

**Comment by TornaxO7** [comment]
Ok wait, I'm sorry, I'm often too hectic. I'll spent some time about the RFC to get a better understanding it.

**Comment by djc** [comment]
No, 2822 is also about MIME. You're confusing MIME messages with IMAP. They're both about email, but otherwise very different things.

**Comment by TornaxO7** [comment]
Ok, so I hope that I found it out now. So [RFC3501](https://datatracker.ietf.org/doc/html/rfc3501) should be a RFC for IMAP and it says in [section 2.3.5](https://datatracker.ietf.org/doc/html/rfc3501#section-2.3.5), it says:

>  A parsed representation of the [RFC-2822] header of the message.
   Note that the IMAP Envelope structure is not the same as an
   [SMTP] envelope.

And the [section 3.6.4](https://datatracker.ietf.org/doc/html/rfc2822#section-3.6.4) of [RFC-2822](https://datatracker.ietf.org/doc/html/rfc2822) says that there should be a `References:` field. The latest [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322), which makes the `RFC 2822` obsolete, says, that there should be a [`References:` field](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6) (or [section 3.6.4](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6)).

Am I on the wrong path again? o.O

**Comment by djc** [comment]
If you look at the formal syntax section of 3501, you can see that the envelope definition there does not contain references.

**Comment by TornaxO7** [comment]
That's strange, than why did they said in the envelope section that it should be the same as the envelope form RFC 2822/5322?

**Comment by TornaxO7** [comment]
Anyway I'm closing this issue now, since you're right, that the envelope definition doesn't contain the `References:` field.
