### ISSUE TITLE
tokio-imap release?

### ISSUE THREAD

**Issue by toxeus** [djc/tokio-imap#162]
tokio-imap didn't have a release for quite some time. Is there a plan to get something out on crates.io?

**Comment by djc** [comment]
It has generally not seen much maintenance, nor much use (as far as I know). Now that async-imap also supports tokio, you might be better off using it, instead?

**Comment by toxeus** [comment]
Thanks for the pointer. I've opened a PR that clarifies current state of affairs in the README so others can benefit from that info, too.
