### ISSUE TITLE
Error parsing HIGHESTMODSEQ that doesn't exist in input stream

### ISSUE THREAD

**Issue by kivikakk** [djc/tokio-imap#21]
I'm doing a pretty simple connection and login attempt:

```rust
    core.run(
        tokio_imap::Client::connect(&config.server, &handle)
            .and_then(|(client, _)| {
                client
                    .call(CommandBuilder::login(&config.username, &config.password))
                    .collect()
            })
            .and_then(|(rd, client)| match rd[0].parsed() {
                Response::Done(_, Status::Ok, _, _) => {
                    futures::future::ok(client.call(CommandBuilder::examine("Inbox")))
                }
                Response::Done(_, Status::No, _, msg) => {
                    println!("login failed: {:?}", msg);
                    futures::future::err(Error::new(ErrorKind::Other, "no"))
                }
                _ => panic!("what"),
            }),
    ).unwrap();
```

It panic(?)s:

```
Error(Tag) at l.183 by ' do_parse ! (
tag_s ! ( "HIGHESTMODSEQ " ) >> num : number_64 >> (
ResponseCode :: HighestModSeq ( num ) ) ) '
00000000        43 41 50 41 42 49 4c 49         CAPABILI
00000008        54 59 20 49 4d 41 50 34         TY IMAP4
00000010        72 65 76 31 20 4c 49 54         rev1 LIT
```

Here's what the full response looks like when manually connecting with `s_client`:

> `1 OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION STATUS=SIZE OBJECTID SAVEDATE XAPPLEPUSHSERVICE LOGINDISABLED XCONVERSATIONS COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE] User logged in SESSIONID=<REDACTED>`

It looks like it's somehow expecting exactly `HIGHESTMODSEQ` here maybe? (Not familiar with nom.)

**Comment by kivikakk** [comment]
I've just realising it's not actually panicking: it continues running despite dumping this.

**Comment by kivikakk** [comment]
This doesn't look like a thing in 0.4. Added the git repo as dependency and it's working. Closing as not a thing.

**Comment by djc** [comment]
Glad that it's working for you after all!
