### ISSUE TITLE
`quoted_data` should return `Needed::Unknown` until no unescaped " found

### ISSUE THREAD

**Issue by duesee** [djc/tokio-imap#27]
I probably noticed a bug in the `quoted` / `quoted_data` parser. Because I am just  becoming acquainted with your code and with nom, I am not sure if I misunderstand something. Here is my failing test:

```rust
#[test]
fn test_quoted() {
    // This is fine.
    assert!(quoted(b"\"I am finished!\"").is_ok());

    // Here, the parser can't know if more data will follow...
    assert_eq!(
        quoted(b"\"I am fini..."), // ...because there is no closing quote.
        Err(Err::Incomplete(Needed::Unknown))
    );
}
```

**Comment by djc** [comment]
Oh, yeah, you're probably right. It's likely that all the parsers written as normal Rust functions instead of using nom combinators have problems like this. So yes, I agree with your assessment. Are you in a position to fix it yourself?

**Comment by duesee** [comment]
Currently, I am trying to find out why some fetch responses are not parsed correctly.
I could commit the test first so that we don't forget about it and fix it later when I'm done with the fetch issue.

By the way: I also did some minor refactorings to group related parsers more closely together so that I can find them better. I also find it useful to distinguish between "core primitives" like `atom`, `astring`, etc. and the "real imap types". If your interested in those changes as weill, I will open a pull request.

**Comment by djc** [comment]
Sure, you can open a PR and we can discuss the best way forward!

**Comment by djc** [comment]
@duesee how did you fare with this? If you still have some unfinished stuff somewhere, I'd like to be able to look at it!

**Comment by duesee** [comment]
Hey, I started implementing some missing parsers, then implemented an ABNF parser in Rust/Nom in the hope to be able to automate the manual process of typing the Nom parsers. To cut the long story short, I got distracted by many other stuff and didn't focused on it for a while :see_no_evil:  I will take a look into it the next days and see if I can at least fix this issue.

**Comment by djc** [comment]
Hah, sounds like a proper yak shaving session! No pressure if you no longer want to work on this, was just wondering about the status.

**Comment by duesee** [comment]
I opened a pull request to merge some of the refactoring and the tests. BTW, what do you think about the idea to generate the parsers? Do you think this can be accomplished?
