### ISSUE TITLE
invalid parsing of gmail imap responses

### ISSUE THREAD

**Issue by softprops** [djc/tokio-imap#36]
This is likely the same error I've seeing in another rust imap project because I think they share the same parser. An issue was opened there first https://github.com/jonhoo/rust-imap/issues/106

I decided to test to see if I could get this crate to work with gmail but it fails on the same imap response parsing

```sh
cargo run --example basic imap.gmail.com {me}@gmail.com {app-password} INBOX
```

```sh
...
failed: Error(Code(...)) during parsing of b"* FLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $NotPhishing $Phishing OIB-Seen-INBOX OIB-Seen-OIB/Business OIB-Seen-OIB/Entertainment OIB-Seen-OIB/Finance OIB-Seen-OIB/Groups OIB-Seen-OIB/Home OIB-Seen-OIB/Jobs OIB-Seen-OIB/News OIB-Seen-OIB/Shopping OIB-Seen-OIB/Social Networking OIB-Seen-OIB/Travel OIB-Seen-[Gmail]/All Mail OIB-Seen-[Gmail]/ImportantOIB-Seen-[Gmail]/Spam OIB-Seen-[Gmail]/Trash)\r\n* OK [PERMANENTFLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $NotPhishing $Phishing OIB-Seen-INBOX OIB-Seen-OIB/Business OIB-Seen-OIB/Entertainment OIB-Seen-OIB/Finance OIB-Seen-OIB/Groups OIB-Seen-OIB/Home OIB-Seen-OIB/Jobs OIB-Seen-OIB/News OIB-Seen-OIB/ShoppingOIB-Seen-OIB/Social Networking OIB-Seen-OIB/Travel OIB-Seen-[Gmail]/All Mail OIB-Seen-[Gmail]/Important OIB-Seen-[Gmail]/Spam OIB-Seen-[Gmail]/Trash \\*)] Flags permitted.\r\n* OK [UIDVALIDITY 673888767] UIDs valid.\r\n* 27102 EXISTS\r\n* 0 RECENT\r\n* OK [UIDNEXT 410518] Predicted next UID.\r\n* OK [HIGHESTMODSEQ 46675148]\r\nA0002 OK [READ-WRITE] INBOX selected. "
```

It was mentioned in the other issue that the parser may not be handling  `]` characters with grace - https://github.com/jonhoo/rust-imap/issues/106#issuecomment-451662087

**Comment by softprops** [comment]
any thoughts @djc ?

**Comment by djc** [comment]
Please, there's no need to ping me again within a day. If you have urgent needs, we can discuss a consulting contract, or consider supporting my work on [Patreon](https://www.patreon.com/dochtman).

What is this `OIB-Seen` thing, is that used by some kind of client you have? It seems it is doing something that's invalid per the spec, since `[` is not allowed in `flag` names, via `atom` -> `atom-specials` -> `resp-specials`.

**Comment by jonhoo** [comment]
I believe it's the name of a gmail folder, and this is how gmail exposes folders as names :/

**Comment by djc** [comment]
But these are flags, not folders, as I understand it. It looks like something reuses folder names for flag names, with a particular prefix. Some of these flags also seem to contain spaces, which I guess could never work, so it seems to me whatever comes up these `OIB-Seen` flags is being buggy.

**Comment by jonhoo** [comment]
It does seem fairly strange. Sadly I don't have a gmail account to test with.. @softprops can you explain the folder layout of these things?

**Comment by djc** [comment]
Also my personal Gmail account which I have been using for 10+ years has nothing like these flags, further supporting my hypothesis that this is not something all GMail users will run into.

**Comment by softprops** [comment]
I'll do some research on the OIB-Seen thing. I can't say I'm an that knowledgeable about the imap protocol. I'm only speaking from the perspective of a Gmail user consuming a crate.

**Comment by softprops** [comment]
The OIB thing seems comes from a company called that offers this service https://getorganizer.com/ -  https://productforums.google.com/forum/#!msg/gmail/8UnHXNy5hzk/yu4JSM3EsIkJ . I've reached out to their customer support to see how I can get these prefixes removed. In the mean time I've created another gmail account and do not experience this issue.  Closing for now.
