### ISSUE TITLE
Parse `FETCH ... BODYSTRUCTURE` response

### ISSUE THREAD

**Issue by lberezy** [djc/tokio-imap#42]
https://github.com/djc/imap-proto/issues/15
https://github.com/djc/imap-proto/pull/16

I was wondering if there was any plans to merge/support BODYSTRUCTURE responses as was discussed when this crate was [imap-proto](https://github.com/djc/imap-proto). It would be useful for upstream crates (such as [rust-imap](https://github.com/jonhoo/rust-imap)).

**Comment by djc** [comment]
I'll see if I can polish up that PR and merge it soon.

**Comment by avitex** [comment]
@djc I'm currently working on a PR to fully parse `BODYSTRUCTURE` in my fork.

**Comment by djc** [comment]
Even better, thanks!
