### ISSUE TITLE
Capability "IMAP4REV1" is not accepted as valid

### ISSUE THREAD

**Issue by link2xt** [djc/tokio-imap#54]
Since PR #47 parser requires `IMAP4rev1` capability to be present. Some IMAP servers send `IMAP4REV1` string instead: https://www.communigate.com/pub/Guide_516.pdf, p. 149

It results in parse error, so I can't connect to such servers with [imap crate](https://github.com/jonhoo/rust-imap), which uses imap-proto parser.

According to [RFC3501](https://tools.ietf.org/html/rfc3501#section-9) "Except as noted otherwise, all alphabetic characters are case-insensitive.".

Thunderbird and mutt accept `IMAP4REV1`.

**Comment by avitex** [comment]
I'll submit a PR to fix this today
