### ISSUE TITLE
New release of imap-proto with #54 fix

### ISSUE THREAD

**Issue by link2xt** [djc/tokio-imap#57]
Since #54 is fixed (I have submitted a test case #56 btw), can you make a new release of imap-proto?

I need it to update PR https://github.com/jonhoo/rust-imap/pull/137 with crates.io dependency. Currently I have to use git.

**Comment by djc** [comment]
Done: https://github.com/djc/tokio-imap/releases/tag/imap-proto-0.9.0.

**Comment by link2xt** [comment]
Thanks!
