### ISSUE TITLE
Parser subscription is probably missing.

### ISSUE THREAD

**Issue by Sergey-Kitov** [djc/tokio-imap#60]
At this point imap-proto tries all the parsers that are implemented. It has to be so for unsolicited responses, but for solicited responses there could be a subscription mechanism, so when an IMAP client using imap-proto library issues a command, it subscribes for parsing related responses and unsubscribes, when Ok/No/Bad for the command is received.

**Comment by djc** [comment]
Is this causing an actual problem for you? You mention a solution, but not the problem that you're trying to solve.

**Comment by skitov** [comment]
It is more like optimization, you avoid doing useless actions by this.

**Comment by djc** [comment]
Sure, I understand that part. I am asking about your use case: what is your use case, and how big of an issue is the library's performance currently?

I would definitely accept a PR for this kind of thing provided it provides some sane API. The simple version off the top of my head would be to have different top-level functions which only parse a subset of the responses.

**Comment by duesee** [comment]
I was looking for something and saw this. From my understanding, a client needs to record all responses and you can't just drop some of them. Also, without parsing, you might not even be able to tell how many bytes to drop. Thus, I think, this issue can be closed.
