### ISSUE TITLE
Check all uses of nstring_utf8 in imap-parser

### ISSUE THREAD

**Issue by link2xt** [djc/tokio-imap#64]
There may be other issues similar to #62, see discussion in #63 

`BodyStructure` parser is probably too restrictive.

**Comment by link2xt** [comment]
Here is the list of things to check:
 - body_fields `id`: probably should be `nstring`, just like message ID, as it is constructed by the user
 - description: probably ok to keep it utf8, it should be 7-bit ASCII anyway see https://tools.ietf.org/html/rfc2045#section-8
 - md5: utf8 is enough
 - date: INTERNALDATE has specific format that is even more restrictive than UTF-8, can be kept UTF-8
 - body_lang: ?
 - body_extension: ?

**Comment by djc** [comment]
Thanks for the investigation. I looked at the specs some more and I think the rest of these should be pretty safe. I added some comments in the source to help keep track of similar issues in the future.
