### ISSUE TITLE
Support parsing RFC 4315 (UIDPLUS Extension) response codes

### ISSUE THREAD

**Issue by Celti** [djc/tokio-imap#66]
[`UIDPLUS`] is useful and desired for implementing any kind of heavy-duty IMAP synchronization tool (e.g., a RIIR of offlineimap). This requires parsing of three additional response codes: `COPYUID`, `APPENDUID`, and `UIDNOTSTICKY`.

[`UIDPLUS`]: https://tools.ietf.org/html/rfc4315

**Comment by djc** [comment]
I won't be able to actively work on this, but would be happy to provide guidance and code review if someone wants to implement this!
