### ISSUE TITLE
Handle short continuation response

### ISSUE THREAD

**Issue by dignifiedquire** [djc/tokio-imap#67]
Some servers (yandex for example) will only send `+\r\n` instead of `+ \r\n` as a continuation response, which the current parser does not accept.

**Comment by djc** [comment]
As I understand it, this is technically invalid per RFC 3501. We'd have to review whether a change like this is likely to break the parser somehow.

Would you be able to contribute a patch to this effect?

**Comment by dignifiedquire** [comment]
> As I understand it, this is technically invalid per RFC 3501.

yes it is :( but unfortunately that does not stop imap server from sending it.. 

> Would you be able to contribute a patch to this effect?

I can send a patch later today, yes
