### ISSUE TITLE
General question about safe string handling.

### ISSUE THREAD

**Issue by duesee** [djc/tokio-imap#78]
Having everything as a `str` is a piece of cake, but strings might become incorrect in certain situations. For example, a mailbox with name `{6}\r\nHello"` might result in a * LIST (...) "" "Hello"", which is invalid. Such problems may lead - in the worst case - to SQLi-like problems.

Possible solution: Wrap String to e.g. `Atom(String)` and implement `From<Atom> for String` and e.g. `TryFrom<String> for Atom`.

The downside is, that the API might become cluttered with too many different types and the need for conversions. I have no middleground proposal how to handle this. Maybe someone knows how dovecot handles it? As an additional note: there is https://tools.ietf.org/html/rfc6855, which might also change the situation somehow.

**Comment by djc** [comment]
I don't think I'd like the wrapping solution here. There's clearly some ease of use vs correctness per spec trade-off here, and I think we should probably decide on a case-by-case basis. If non-UTF-8 content is forbidden from showing up then I don't think passing `&[u8]` up to the API user is productive. In general I prefer to err on the side of correctness, but the trade-off is clearly real. (See also #63 for example.)

**Comment by djc** [comment]
Since there doesn't seem to be any clear actionable path forward here and I hope I've answered your question, I'm going to close this for now. Feel free to reopen or open new issues if you have concrete ideas on how to improve the current state of things.
