### ISSUE TITLE
Deal with upstream `StateStream` change

### ISSUE THREAD

**Issue by sanmai-NL** [djc/tokio-imap#8]
> btw, there are some issues with the StateStream changes in version 0.2. so I'm thinking we may need to fork it (@djc)

https://github.com/sfackler/futures-state-stream/pull/8#issuecomment-339105967

https://github.com/sfackler/futures-state-stream/issues/11#issuecomment-344435705

**Comment by sanmai-NL** [comment]
Question, what was your motivation to use `futures-state-stream` in the first place, @djc?

**Comment by djc** [comment]
The way it can store the transport while traversing the stream and then yields it at the end of the stream seems to fit really well with how futures work, and seems to map well on how IMAP works.

**Comment by sanmai-NL** [comment]
Can the current design gain from the `impl Trait` feature of Rust, additionally or alternatively?

**Comment by djc** [comment]
This is no longer in use, closing.
