### ISSUE TITLE
Use `ToSocketAddrs` in `Client::connect`

### ISSUE THREAD

**Issue by dario23** [djc/tokio-imap#9]
in alignment with tokio's `net::TcpStream::connect` it could be argued that taking any `ToSocketAddrs` (instead of currently &str) would be better.

as that would be an api-breaking change in any case, and isn't a lot of code to write, i refrained from sending a pull request.

**Comment by djc** [comment]
Hey, thanks for the bug report. "It could be argued" is a little abstract to me. Do you have an actual use case where it's better, can you tell me more about it? At this stage I don't have a problem accepting API-breaking changes, and your PR would still be appreciated. 😄 (Though maybe let's discuss the use case first.)

**Comment by sanmai-NL** [comment]
It’s not a breaking change if we just add another function that can take a `SocketAddr`, and (I’d say) deprecate `Client::connect`.

One benefit of that is that port 993 is currently hardcoded in `Client::connect`, whereas it needn’t be when a `SocketAddr` is accepted. Also, we lose the overhead in formatting strings/constructing a socket where a socket may already be available in the caller.

**Comment by djc** [comment]
I'm not interested for now in going through deprecation dances, there are no large users anyway.

If we do go the route of accepting `ToSocketAddrs`, we also have to clarify that TLS is (at least currently) required for tokio-imap to work.

**Comment by djc** [comment]
Ah, so the other reason not to do this is that we still need the server name for the TLS handshake. So best case, `connect()` then has to take two arguments, which I feel doesn't really improve things. I'll check if there's a way to get rid of the formatting string overhead some other way.

**Comment by sanmai-NL** [comment]
What about making setting up a TCP stream the concern of the caller, like in [the h2 client](https://github.com/carllerche/h2/blob/ef99f99ae1182a6b4661606def2cd11490798661/examples/client.rs)?

Concerning most simple uses of string formatting, a faster alternative is to use [`concat()`](https://doc.rust-lang.org/alloc/slice/trait.SliceConcatExt.html#tymethod.concat).

**Comment by djc** [comment]
I already found a different solution to prevent the string formatting:

```diff
--- a/src/client/mod.rs
+++ b/src/client/mod.rs
@@ -31,8 +31,7 @@ pub struct Client {
 
 impl Client {
     pub fn connect(server: &str) -> ImapConnectFuture {
-        let addr = format!("{}:993", server);
-        let addr = addr.to_socket_addrs().unwrap().next().unwrap();
+        let addr = (server, 993).to_socket_addrs().unwrap().next().unwrap();
         ImapConnectFuture::TcpConnecting(TcpStream::connect(&addr), server.to_string())
     }
```

It would be really helpful if both of you were more concrete about your requirements: please tell me about your problems, instead of the solutions that you see.

We can add a second `Client` constructor that takes an `ImapTransport` (which should probably be a more general type), so that the connection setup and TLS handshake are both left to the user.
