### ISSUE TITLE
Retrieve the SectionPath of one BodyStructure

### ISSUE THREAD

**Issue by yageek** [djc/tokio-imap#92]
I'm using currently the `imap_proto` crate to retrieve some specific attachment inside an email.

The process is the following one:

1. Retrieve the body structure of the email using a `FETCH BODYSTRUCTURE` request
2. Looking for some interesting section(s) inside this email
3. Fetching the corresponding sestion using a `FETCH BODY[<section>]` element

To retrieve the appropriate `<section>`, I need to parse again the tree of `BodyStructure` enum to recompute the appropriate section identifier.

Is this the correct way to go or did I misses something in the crate? 
Is there any plan to already provide inside `BodyStructure` in the future?

**Comment by djc** [comment]
I don't have much experience with this part of the API, since I haven't really used it myself. Maybe you can explain more by some showing some code samples?

**Comment by yageek** [comment]
You can query the server about the body structure of one message to download only the part you are interested in.

Using a `FETCH BODYSTRUCTURE` request, you retrieve a tree of elements/nested lists representing how the body is organized.

To fetch one or multiple part, yon can send a `BODY[<section>]` request where `<section>` represents the identifier deduced from the `BODYSTRUCTURE`.

(See [some examples here](http://sgerwk.altervista.org/imapbodystructure.html)).

Here, it means that from  a tree of `BodyStructure` enum variants like:

![CJGMT](https://user-images.githubusercontent.com/170917/92931399-b121f400-f443-11ea-9850-a4225586d794.png)

We need to find  the identifiers by parsing the tree using this pattern:
![2I7WC](https://user-images.githubusercontent.com/170917/92931452-c434c400-f443-11ea-870b-c31ca6245e3d.png)

**Comment by djc** [comment]
As mentioned in my last comment, I really need some code samples to make sense of what you're asking here.

**Comment by yageek** [comment]
Sorry to have eluded this part. 

Let's take one response sample from the link upwards that is an answer to a `FETCH BODYSTRUCTURE` request:

```
* 1569 FETCH (BODYSTRUCTURE (((("TEXT" "PLAIN" ("CHARSET" "ISO-8859-1") NIL NIL "QUOTED-PRINTABLE" 833 30 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "ISO-8859-1") NIL NIL "QUOTED-PRINTABLE" 3412 62 NIL ("INLINE" NIL) NIL) "ALTERNATIVE" ("BOUNDARY" "2__=fgrths") NIL NIL)("IMAGE" "GIF" ("NAME" "485039.gif") "<2__=lgkfjr>" NIL "BASE64" 64 NIL ("INLINE" ("FILENAME" "485039.gif")) NIL) "RELATED" ("BOUNDARY" "1__=fgrths") NIL NIL)("APPLICATION" "PDF" ("NAME" "title.pdf") "<1__=lgkfjr>" NIL "BASE64" 333980 NIL ("ATTACHMENT" ("FILENAME" "title.pdf")) NIL) "MIXED" ("BOUNDARY" "0__=fgrths") NIL NIL))
```
To be able to find the corresponding ID of the different part, I need to parse it again. I may do something like this (parsing algorithm may not bee correct yet :D )

```rust
use imap_proto::BodyStructure;

pub struct BodyStructParser<'a> {
    root: &'a BodyStructure<'a>,
    prefix: Vec<u32>,
    iter: u32,
}

impl<'a> BodyStructParser<'a> {
    pub fn new(root: &'a BodyStructure<'a>) -> Self {
        BodyStructParser {
            root,
            prefix: vec![],
            iter: 1,
        }
    }

    pub fn parse(&mut self) {
        self.inner_parse(self.root);
    }

    fn inner_parse(&mut self, node: &BodyStructure) {
        match node {
            BodyStructure::Multipart { bodies, .. } => {
                println!("[MULTIPART] {:?}", self.prefix);

                for (i, n) in bodies.iter().enumerate() {
                    self.iter += i as u32;
                    self.prefix.push(self.iter);
                    self.inner_parse(n);
                    self.prefix.pop();
                }
                self.iter = 1;
            }
            BodyStructure::Text { common, .. } => {
                println!("[{}] {:?}", common.ty.ty, self.prefix);
            }
            BodyStructure::Message { common, .. } => {
                println!("[{}] {:?}", common.ty.ty, self.prefix);
            }
            BodyStructure::Basic { common, .. } => {
                println!("[{}] {:?}", common.ty.ty, self.prefix);
            }
        }
    }
}
```

A simple test function to use it:

```rust
 #[test]
    fn test_imap() {
       // Include the corresponding payload as bytes for test
        let mut test = include_bytes!("attachment_response.txt").to_vec(); 
        test.extend_from_slice(b"\r\n");

        let (_, resp) = imap_proto::parse_response(&test).unwrap();
        match resp {
            imap_proto::Response::Fetch(_, f) => {
                let bodystructure = f
                    .iter()
                    .flat_map(|f| match f {
                        AttributeValue::BodyStructure(e) => Some(e),
                        _ => None,
                    })
                    .next()
                    .unwrap();

                let mut parser = BodyStructParser::new(bodystructure);
                parser.parse();
            }
            _ => panic!("False"),
        };
    }
```

This gave as output:
```
[MULTIPART] []
[MULTIPART] [1]
[MULTIPART] [1, 1]
[TEXT] [1, 1, 1]
[TEXT] [1, 1, 2]
[IMAGE] [1, 2]
[APPLICATION] [2]
```

Then I could download only the part I want using the ID (ex. [1,2] for the image):

```rust
let result = imap_session.fetch(&email_id, "BODY[1.2]")?;
let fetch = result.first().unwrap();

// body: Vec<u8>
let body = fetch
        .section(&SectionPath::Part(
            vec![1,2],
            None,
        ))
        .unwrap()
        .to_vec();
```

**Comment by djc** [comment]
It's still unclear to me what you actually want from this library. This crate is intended as a simple way to create IMAP protocol commands and parse responses; higher-level functionality is more or less intentionally left to other layers. That said, if you want to propose an enhancement feel free to send a PR and I will review it.

**Comment by yageek** [comment]
Sorry for the lack of clarity 😬 I would probably do a PR in the near future. It may be too high level for the purpose of this crate but I would think the use case is pretty common 🤔.

**Comment by mmirate** [comment]
I think maybe #111 ought to have closed this issue?

**Comment by djc** [comment]
Yup, thanks for pointing that out!
